### ISSUE TITLE
Unable to destroy webview 

### ISSUE THREAD

**Issue by andrewChris** [braintree/popup-bridge-ios#20]
### General information

* iOS Version and Device: iOS 11 and above
* Integration type and version: CocoaPods latest version (pod 'PopupBridge')

### Issue description

We have an issue where the deinit method in our view controller is not being called because the Popup bridge holds a strong reference our webview as per the below line in the POPPopupBridge.m class: 

@property (nonnull, nonatomic, strong) WKWebView *webView;

As it is a nonnull and strong we are unable to set the instance to nil which is causing a memory leak that we are unable to fix.

**Comment by demerino** [comment]
We're unable to recreate the memory leak you've described, can you share a screenshot of the retain cycle you're seeing after releasing your webView?

**Comment by andrewChris** [comment]
Thank you for getting back to me, I managed to fix the issue without accessing the popupbridge webview property. 

Thanks again.
