### ISSUE TITLE
Feature Request: Swift Package Manager Support

### ISSUE THREAD

**Issue by ragzy15** [braintree/popup-bridge-ios#27]
Hi,
I was wondering if you guys can provide support for Swift Package Manager, it will be great to use with your library.

**Comment by billwerges** [comment]
Hi @ragzy15,

Yes, we will be looking into supporting Swift Package Manager for this project.

**Comment by Tawa** [comment]
Hey @billwerges 
Any updates on SPM support?

**Comment by scannillo** [comment]
Hi @Tawa - we don't currently have an ETA but plan to add support for SPM in the near future. We will keep you posted in this thread!

**Comment by Nonnus** [comment]
@scannillo +1 on this request, please keep in mind that carthage or cocoapods managed 3rd party dependencies prevent using iOS simulator on m1 machines which, as you can understand, is not ideal at all. Your sdk is one of the few ones we use on our company that is currently blocking us from acquiring m1 machines to augment our ci server farm

**Comment by sestevens** [comment]
We've just released [version 1.2.0](https://github.com/braintree/popup-bridge-ios/releases/tag/1.2.0), which includes support for Swift Package Manager.

**Comment by Nonnus** [comment]
@sestevens these are some great news! thanks a lot
