### ISSUE TITLE
Remove Excluded architectures flag ( Apple M1 )

### ISSUE THREAD

**Issue by jakguel** [braintree/popup-bridge-ios#36]
### General information

* iOS Version and Device: Any IOS Emulator on M1 Processor
* Integration type and version: CocoaPods

### Issue description

Following line in PopupBridge.release and PopupBridge.debug files (Pods/PopupBridge/SupportFiles) cause a compilation Error on my M1. 
```EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64```
I am then forced to use Rosetta which causes runtime Problems with my Capacitor App.

After removing the line above from the following files i was able to compile and run the app.
```
Pods/PupupBridge/SuppoprtFiles/PupupBridge.debug
Pods/PupupBridge/SuppoprtFiles/PupupBridge.release
Targets Support Files/Pods-App/Pods-App.debug
Targets Support Files/Pods-App/Pods-App.release
```

The ```EXCLUDED_ARCHS``` Flag in the Podspec of this project causes also  my Pods-App to contain that flag, which has an impact on my whole project.

**Comment by jaxdesmarais** [comment]
Hello @jakguel -

Thanks for using the Popup Bridge SDK. I've run both the [sample app in this repo](https://github.com/braintree/popup-bridge-ios#sample-app) as well as a local demo app pulling in the pod for this SDK without issue on an M1. 

Are these specific steps you are using to reproduce this issue that we can try on our end? Are you able to run the sample app linked above on your end?
