### ISSUE TITLE
Readme: Unclear where to implement step 3 Integrate PopupBridge with the WKWebView:

### ISSUE THREAD

**Issue by einmalick** [braintree/popup-bridge-ios#40]
It is not clear where to implement step 3 Integrate PopupBridge with the WKWebView in an Expo application.

Please enhance readme.

**Comment by einmalick** [comment]
In react native + Expo applications RNCWKWebvie is used instead of WKWebview.

**Comment by jaxdesmarais** [comment]
Hello @einmalick -

Thanks for reaching out. We do not officially support React Native, Expo, or any compile to native frameworks. As I understand `RNCWKWebview` uses `WKWebview ` under the hood in the latest version so there may be a way to access and inject the webivew as expected in a React Native + Expo project. That said, our recommend and supported approach would be to use `WebKit` directly.

Please feel free to take a look at the [Demo app within the SDK](https://github.com/braintree/popup-bridge-ios/tree/master/Demo/Demo) for an example of how to incorporate Popup Bridge into your project.
