### ISSUE TITLE
iOS17/Xcode15 Compatability Check

### ISSUE THREAD

**Issue by pavm035** [braintree/popup-bridge-ios#59]
Hi,

We are using this SDK v1.2.0 and we are targeting for iOS17 release soon, So we wanted to confirm if this SDK is compatible with iOS17/Xcode15?

**Comment by scannillo** [comment]
👋 Hi @pavm035 - thank you for bringing this to our attention. This is something we can verify and test soon. In the meantime, if you encounter any bugs specific to Xcode 15 and iOS 17, please let us know!

(Ticket DTBTSDK-2914 for internal tracking)

**Comment by scannillo** [comment]
Hi @pavm035 - I was able to use both PopupBridge v2.0.0-beta1 & 1.2.0 fine with Xcode 15 beta & iOS 17.

We will soon update our CI to test for the newest Xcode as well as Xcode 15.

**Comment by scannillo** [comment]
If you have any feedback on the V2 beta, please do let us know! See our [Migration guide](https://github.com/braintree/popup-bridge-ios/blob/master/V2_MIGRATION.md) for how to update 😄

**Comment by pavm035** [comment]
Hi @scannillo  Thanks for the confirmation
