### ISSUE TITLE
Xcode 16/ iOS18 Compatibility check 

### ISSUE THREAD

**Issue by pavm035** [braintree/popup-bridge-ios#65]
Hi,

This is just general query to confirm the official PopupBridge SDK version that's compatible with Xcode 16/iOS18

Current version we are using: 2.1.0

**Comment by scannillo** [comment]
Hi @pavm035 - yes we tested the PopupBridge SDK with Xcode 16 and iOS 18. We encountered no issues on the latest version v2.1.0.

Feel free to comment or re-open this thread if you encounter any problems!

**Comment by pavm035** [comment]
Thanks for the update
